import React, { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { User, Mail, Lock, ShieldCheck, ArrowRight } from "lucide-react";
import { useAuth } from "../../hooks/useAuth";
import { translations } from "../../constants/translations";
import { useLanguage } from "../../hooks/useLanguage";

const Register = () => {
  const navigate = useNavigate();
  const { register } = useAuth();
  const { language } = useLanguage();

  // --- STATE ---
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    password: "",
    confirm: "",
    level: { passed: [], current: "Basic" },
  });
  const [isAgreed, setIsAgreed] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // --- USERNAME GENERATOR (Japanese Themed) ---
  const generateReadableUsername = () => {
    const adjectives = [
      "swift",
      "silent",
      "golden",
      "rising",
      "brave",
      "zen",
      "hidden",
      "mystic",
    ];
    const nouns = [
      "ninja",
      "shrine",
      "dragon",
      "sakura",
      "spirit",
      "katana",
      "shogun",
      "wave",
    ];

    const adj = adjectives[Math.floor(Math.random() * adjectives.length)];
    const noun = nouns[Math.floor(Math.random() * nouns.length)];
    const number = Math.floor(100 + Math.random() * 899);

    return `${adj}_${noun}_${number}`;
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (formData.password !== formData.confirm) {
      setError("Passwords do not match");
      return;
    }

    setLoading(true);
    setError(null);

    const autogeneratedUsername = generateReadableUsername();

    try {
      await register({
        name: formData.name,
        email: formData.email,
        password: formData.password,
        username: autogeneratedUsername,
        level: formData.level,
      });
      navigate("/");
    } catch (err) {
      console.error("Error registering user", err.message);
      setError(err.response?.data?.message || err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-background flex flex-col md:flex-row-reverse font-sans overflow-hidden">
      {/* FORM SIDE */}
      <div className="flex-1 flex items-center justify-center p-6 sm:p-8 md:p-16 z-10">
        <div className="w-full max-w-md animate-in fade-in slide-in-from-right duration-700">
          <Link to="/" className="inline-block mb-10">
            <img src="/assets/logo.png" alt="Logo" className="h-16" />
          </Link>

          <h1 className="text-3xl md:text-4xl font-black text-text mb-2">
            Join DOA
          </h1>
          <p className="text-text/50 font-bold mb-8 tracking-widest text-xs sm:text-sm italic">
            Start your stress-free free courses
          </p>

          {error && (
            <div className="mb-6 p-4 bg-error/10 border border-error/20 rounded-2xl text-error text-xs font-black animate-shake text-center">
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-5">
            <div className="space-y-1">
              <label className="text-xs font-black text-text/40 ml-1">
                {translations[language].name}
              </label>
              <div className="relative group">
                <User
                  className="absolute left-4 top-1/2 -translate-y-1/2 text-text/30 group-focus-within:text-primary transition-colors"
                  size={18}
                />
                <input
                  name="name"
                  type="text"
                  required
                  onChange={handleChange}
                  className="w-full bg-surface border border-border rounded-2xl py-4 pl-12 pr-4 text-base text-text font-bold outline-none focus:border-primary focus:ring-4 focus:ring-primary/10 transition-all"
                />
              </div>
            </div>

            <div className="space-y-1">
              <label className="text-xs font-black text-text/40 ml-1">
                {translations[language].email}
              </label>
              <div className="relative group">
                <Mail
                  className="absolute left-4 top-1/2 -translate-y-1/2 text-text/30 group-focus-within:text-primary transition-colors"
                  size={18}
                />
                <input
                  name="email"
                  type="email"
                  required
                  onChange={handleChange}
                  className="w-full bg-surface border border-border rounded-2xl py-4 pl-12 pr-4 text-base text-text font-bold outline-none focus:border-primary focus:ring-4 focus:ring-primary/10 transition-all"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-1">
                <label className="text-xs font-black text-text/40 ml-1">
                  {translations[language].password}
                </label>
                <div className="relative group">
                  <Lock
                    className="absolute left-4 top-1/2 -translate-y-1/2 text-text/30 group-focus-within:text-primary transition-colors"
                    size={18}
                  />
                  <input
                    name="password"
                    type="password"
                    required
                    placeholder="••••••"
                    onChange={handleChange}
                    className="w-full bg-surface border border-border rounded-2xl py-4 pl-12 pr-4 text-base text-text font-bold outline-none focus:border-primary focus:ring-4 focus:ring-primary/10 transition-all"
                  />
                </div>
              </div>
              <div className="space-y-1">
                <label className="text-xs font-black text-text/40 ml-1">
                  Confirm
                </label>
                <div className="relative group">
                  <ShieldCheck
                    className="absolute left-4 top-1/2 -translate-y-1/2 text-text/30 group-focus-within:text-primary transition-colors"
                    size={18}
                  />
                  <input
                    name="confirm"
                    type="password"
                    required
                    placeholder="••••••"
                    onChange={handleChange}
                    className="w-full bg-surface border border-border rounded-2xl py-4 pl-12 pr-4 text-base text-text font-bold outline-none focus:border-primary focus:ring-4 focus:ring-primary/10 transition-all"
                  />
                </div>
              </div>
            </div>

            {/* LEGAL CHECKBOX */}
            <div className="flex items-center gap-3 py-2">
              <input
                type="checkbox"
                id="terms"
                className="w-5 h-5 rounded border-border text-primary focus:ring-primary cursor-pointer transition-all"
                checked={isAgreed}
                onChange={(e) => setIsAgreed(e.target.checked)}
              />
              <label
                htmlFor="terms"
                className="text-xs font-bold text-text/50 leading-none cursor-pointer select-none"
              >
                I agree to the{" "}
                <Link
                  to="/terms-of-service"
                  className="text-primary hover:underline"
                >
                  Terms
                </Link>{" "}
                and{" "}
                <Link
                  to="/privacy-policy"
                  className="text-primary hover:underline"
                >
                  Privacy
                </Link>
              </label>
            </div>

            {/* BUTTON LOGIC: Disabled unless loading is false AND isAgreed is true */}
            <button
              type="submit"
              disabled={loading || !isAgreed}
              className="w-full bg-primary text-inverted py-4 rounded-2xl font-black text-sm sm:text-base tracking-widest flex items-center justify-center gap-3 hover:shadow-2xl hover:shadow-primary/30 transition-all active:scale-95 group mt-4 disabled:opacity-30 disabled:grayscale disabled:cursor-not-allowed"
            >
              {loading ? (
                <div className="flex flex-col items-center gap-1">
                  <h2 className="text-sm md:text-base font-black   animate-pulse">
                    {translations[language].processing}
                    <span className="text-inverted/50">...</span>
                  </h2>
                </div>
              ) : (
                <>
                  {translations[language].register}{" "}
                  <ArrowRight
                    size={20}
                    className="group-hover:translate-x-1 transition-transform"
                  />
                </>
              )}
            </button>
          </form>

          <p className="mt-8 text-center text-sm font-bold text-text/40  tracking-tight">
            Already a member?{" "}
            <Link
              to="/login"
              className="text-primary font-black hover:underline ml-1"
            >
              Login here
            </Link>
          </p>
        </div>
      </div>

      {/* VISUAL SIDE */}
      <div className="hidden md:flex flex-1 bg-surface relative items-center justify-center p-12 overflow-hidden border-r border-border">
        <div className="absolute top-[-10%] right-[-10%] w-[500px] h-[500px] bg-primary/5 rounded-full blur-[100px]" />
        <div className="relative z-10 text-center">
          <div className="mb-10 inline-flex items-center justify-center w-24 h-24 rounded-3xl bg-primary text-inverted rotate-12 shadow-2xl font-black text-4xl">
            あ
          </div>
          <h2 className="text-4xl lg:text-5xl font-black tracking-tighter text-text leading-tight mb-4">
            Level up your <br />
            <span className="text-primary italic">Experience</span>
          </h2>
          <p className="text-text/50 font-bold text-xs sm:text-sm">
            Join thousands of students worldwide
          </p>
        </div>
      </div>
    </div>
  );
};

export default Register;
